title: salento.dev
description: Homepage di Salento Dev
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# google_analytics: [Your Google Analytics tracking ID]